# Generated by Django 5.1.2 on 2024-10-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='privilegios',
            field=models.BooleanField(max_length=50),
        ),
    ]
