# Generated by Django 5.1.2 on 2024-10-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_email_alter_usuarios_privilegios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='grupo',
            field=models.IntegerField(choices=[(1, 'Grupo 1'), (2, 'Grupo 2'), (3, 'Grupo 3'), (4, 'Grupo 4'), (5, 'Grupo 5')], default=1),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='telefono1',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='telefono2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
